export const heritageTypes = [
  'Archaeological & Historical Places',
  'Cultural Landscapes',
  'Natural Heritage',
]

export const creativeSegments = [
  'Cultural & Natural Heritage',
  'Performance & Celebration',
  'Visual Arts & Crafts',
  'Books & Press',
  'Audio Visual & Interactive Media',
  'Design & Creative',
]

export const publicationStates = [
  { value: 'draft', label: 'Draft' },
  { value: 'scheduled', label: 'Scheduled' },
  { value: 'published', label: 'Published' },
  { value: 'archived', label: 'Archived' },
]

export const adminResources = {
  heritage: {
    table: 'heritage_items',
    label: 'Heritage places',
    singular: 'heritage place',
    shortLabel: 'Heritage',
    description: 'Archaeological places, cultural landscapes and natural heritage.',
    icon: 'landmark',
    titleField: 'title',
    subtitleField: 'location',
    publicPath: (item) => `/heritage/${item.slug}`,
    columns: [
      { key: 'title', label: 'Place' },
      { key: 'type', label: 'Heritage type' },
      { key: 'location', label: 'Location' },
    ],
    fields: [
      { key: 'title', label: 'Title', required: true, wide: true },
      { key: 'slug', label: 'URL slug', required: true },
      { key: 'location', label: 'Location', required: true },
      { key: 'region', label: 'Region' },
      { key: 'type', label: 'Heritage type', type: 'select', options: heritageTypes, required: true },
      { key: 'tag', label: 'Editorial tag', required: true },
      { key: 'image', label: 'Feature image', type: 'asset', assetKind: 'image', required: true, wide: true },
      { key: 'summary', label: 'Short summary', type: 'textarea', rows: 3, wide: true },
      { key: 'body', label: 'Full story', type: 'textarea', rows: 7, wide: true },
      { key: 'website', label: 'Official website', type: 'url', wide: true },
      { key: 'sort_order', label: 'Display order', type: 'number', defaultValue: 0 },
    ],
  },
  museums: {
    table: 'museums',
    label: 'Museums & collections',
    singular: 'museum',
    shortLabel: 'Museums',
    description: 'Institutions, collections, opening information and visitor stories.',
    icon: 'museum',
    titleField: 'title',
    subtitleField: 'location',
    publicPath: (item) => `/museums/${item.slug}`,
    columns: [
      { key: 'title', label: 'Museum' },
      { key: 'location', label: 'Location' },
      { key: 'hours', label: 'Opening hours' },
    ],
    fields: [
      { key: 'title', label: 'Name', required: true, wide: true },
      { key: 'slug', label: 'URL slug', required: true },
      { key: 'location', label: 'Location', required: true },
      { key: 'hours', label: 'Opening hours' },
      { key: 'image', label: 'Feature image', type: 'asset', assetKind: 'image', required: true, wide: true },
      { key: 'detail', label: 'Card description', type: 'textarea', rows: 3, required: true, wide: true },
      { key: 'body', label: 'Full visitor story', type: 'textarea', rows: 7, wide: true },
      { key: 'website', label: 'Official website', type: 'url', wide: true },
      { key: 'sort_order', label: 'Display order', type: 'number', defaultValue: 0 },
    ],
  },
  performances: {
    table: 'performances',
    label: 'Performance traditions',
    singular: 'performance tradition',
    shortLabel: 'Performance',
    description: 'Performing arts, music, ceremonies and living traditions.',
    icon: 'music',
    titleField: 'title',
    subtitleField: 'people',
    publicPath: () => '/performance',
    columns: [
      { key: 'title', label: 'Tradition' },
      { key: 'people', label: 'Community' },
      { key: 'label', label: 'Editorial label' },
    ],
    fields: [
      { key: 'title', label: 'Title', required: true, wide: true },
      { key: 'slug', label: 'URL slug', required: true },
      { key: 'people', label: 'People or community', required: true },
      { key: 'label', label: 'Editorial label', required: true },
      { key: 'image', label: 'Feature image', type: 'asset', assetKind: 'image', required: true, wide: true },
      { key: 'description', label: 'Short description', type: 'textarea', rows: 3, required: true, wide: true },
      { key: 'body', label: 'Full story', type: 'textarea', rows: 7, wide: true },
      { key: 'sort_order', label: 'Display order', type: 'number', defaultValue: 0 },
    ],
  },
  events: {
    table: 'events',
    label: 'Events calendar',
    singular: 'event',
    shortLabel: 'Events',
    description: 'Festivals, fairs, performances, exhibitions and public programmes.',
    icon: 'calendar',
    titleField: 'title',
    subtitleField: 'place',
    publicPath: (item) => `/events/${item.slug}`,
    columns: [
      { key: 'title', label: 'Event' },
      { key: 'event_date', label: 'Date', type: 'date' },
      { key: 'place', label: 'Place' },
      { key: 'type', label: 'Type' },
    ],
    fields: [
      { key: 'title', label: 'Event title', required: true, wide: true },
      { key: 'slug', label: 'URL slug', required: true },
      { key: 'type', label: 'Event type', required: true },
      { key: 'place', label: 'Venue or place', required: true, wide: true },
      { key: 'event_date', label: 'Start date', type: 'date' },
      { key: 'end_date', label: 'End date', type: 'date' },
      { key: 'day', label: 'Display day', required: true },
      { key: 'month', label: 'Display month', required: true },
      { key: 'image', label: 'Feature image', type: 'asset', assetKind: 'image', required: true, wide: true },
      { key: 'summary', label: 'Summary', type: 'textarea', rows: 3, wide: true },
      { key: 'body', label: 'Full event description', type: 'textarea', rows: 7, wide: true },
      { key: 'booking_url', label: 'Booking or information URL', type: 'url', wide: true },
      { key: 'sort_order', label: 'Display order', type: 'number', defaultValue: 0 },
    ],
  },
  podcasts: {
    table: 'podcasts',
    label: 'Podcasts & audio',
    singular: 'podcast episode',
    shortLabel: 'Podcasts',
    description: 'Episodes, oral histories, recordings and listening metadata.',
    icon: 'podcast',
    titleField: 'title',
    subtitleField: 'category',
    publicPath: () => '/media-library',
    columns: [
      { key: 'number', label: 'Episode' },
      { key: 'title', label: 'Title' },
      { key: 'category', label: 'Category' },
      { key: 'length', label: 'Length' },
    ],
    fields: [
      { key: 'title', label: 'Episode title', required: true, wide: true },
      { key: 'slug', label: 'URL slug', required: true },
      { key: 'number', label: 'Episode number', required: true },
      { key: 'category', label: 'Category', required: true },
      { key: 'guest', label: 'Guest or episode line', required: true, wide: true },
      { key: 'length', label: 'Duration', required: true },
      { key: 'image', label: 'Cover image', type: 'asset', assetKind: 'image', required: true, wide: true },
      { key: 'audio_url', label: 'Episode audio', type: 'asset', assetKind: 'audio', wide: true },
      { key: 'description', label: 'Episode description', type: 'textarea', rows: 5, wide: true },
      { key: 'sort_order', label: 'Display order', type: 'number', defaultValue: 0 },
    ],
  },
  creatives: {
    table: 'creative_profiles',
    label: 'Creative directory',
    singular: 'creative profile',
    shortLabel: 'Directory',
    description: 'Artists, studios, organisations, services and creative businesses.',
    icon: 'palette',
    titleField: 'name',
    subtitleField: 'location',
    publicPath: (item) => `/directory/${item.slug}`,
    columns: [
      { key: 'name', label: 'Profile' },
      { key: 'segment', label: 'Creative sector' },
      { key: 'location', label: 'Location' },
      { key: 'verified', label: 'Verified', type: 'boolean' },
    ],
    fields: [
      { key: 'name', label: 'Profile name', required: true, wide: true },
      { key: 'slug', label: 'URL slug', required: true },
      { key: 'segment', label: 'Creative sector', type: 'select', options: creativeSegments, required: true },
      { key: 'location', label: 'Location', required: true },
      { key: 'focus', label: 'Focus areas', required: true, wide: true },
      { key: 'image', label: 'Profile image', type: 'asset', assetKind: 'image', required: true, wide: true },
      { key: 'description', label: 'Profile description', type: 'textarea', rows: 6, required: true, wide: true },
      { key: 'website', label: 'Website', type: 'url' },
      { key: 'email', label: 'Public email', type: 'email' },
      { key: 'sort_order', label: 'Display order', type: 'number', defaultValue: 0 },
      { key: 'verified', label: 'Verified profile', type: 'boolean', defaultValue: false },
    ],
  },
  media: {
    table: 'media_items',
    label: 'Films, tours & interactive media',
    singular: 'media story',
    shortLabel: 'Media hub',
    description: 'Films, virtual tours, archive recordings, audio and interactive experiences.',
    icon: 'video',
    titleField: 'title',
    subtitleField: 'media_type',
    publicPath: () => '/media-library',
    columns: [
      { key: 'title', label: 'Title' },
      { key: 'media_type', label: 'Format' },
      { key: 'category', label: 'Collection' },
      { key: 'location', label: 'Location' },
    ],
    fields: [
      { key: 'title', label: 'Title', required: true, wide: true },
      { key: 'slug', label: 'URL slug', required: true },
      { key: 'media_type', label: 'Media format', required: true },
      { key: 'category', label: 'Collection or category', required: true },
      { key: 'location', label: 'Location' },
      { key: 'duration', label: 'Duration' },
      { key: 'image', label: 'Cover image', type: 'asset', assetKind: 'image', required: true, wide: true },
      { key: 'media_url', label: 'Hosted media file', type: 'asset', assetKinds: ['audio', 'video'], wide: true },
      { key: 'embed_url', label: 'External embed URL', type: 'url', wide: true },
      { key: 'source_name', label: 'Source or rights holder', required: true },
      { key: 'source_url', label: 'Source page', type: 'url', required: true, wide: true },
      { key: 'description', label: 'Description', type: 'textarea', rows: 6, required: true, wide: true },
      { key: 'sort_order', label: 'Display order', type: 'number', defaultValue: 0 },
    ],
  },
}

export const workflowResources = {
  contact: {
    table: 'contact_messages',
    label: 'Contact inbox',
    singular: 'message',
    description: 'Questions and enquiries sent through the public contact page.',
    icon: 'mail',
    titleField: 'subject',
    personField: 'name',
    emailField: 'email',
    bodyField: 'message',
    statusField: 'status',
    statuses: ['new', 'in_progress', 'resolved', 'spam'],
  },
  submissions: {
    table: 'submissions',
    label: 'Contribution queue',
    singular: 'submission',
    description: 'Stories, events, profiles and corrections awaiting editorial review.',
    icon: 'inbox',
    titleField: 'title',
    personField: 'name',
    emailField: 'email',
    bodyField: 'description',
    statusField: 'status',
    statuses: ['received', 'reviewing', 'accepted', 'declined'],
  },
  subscribers: {
    table: 'newsletter_subscribers',
    label: 'Newsletter audience',
    singular: 'subscriber',
    description: 'Subscribers, acquisition sources and active mailing status.',
    icon: 'send',
    titleField: 'email',
    personField: 'source',
    statusField: 'active',
  },
}

export const adminRoles = [
  { value: 'member', label: 'Member', description: 'Save items and manage their own contributions.' },
  { value: 'editor', label: 'Editor', description: 'Create and manage published cultural content.' },
  { value: 'admin', label: 'Administrator', description: 'Full studio access, workflows and member roles.' },
]

export const resourceEntries = Object.entries(adminResources)
export const workflowEntries = Object.entries(workflowResources)
