-- Expand Cultural & Natural Heritage with the current UNESCO register and
-- the places needed by the combined heritage-and-museums frontend.

insert into public.heritage_items
  (slug, title, location, type, image, tag, summary, body, region, published, sort_order)
values
  ('mount-mulanje', 'Mount Mulanje', 'Mulanje', 'Cultural Landscapes', 'https://commons.wikimedia.org/wiki/Special:Redirect/file/Mount%20Mulanje.jpg?width=1600', 'UNESCO World Heritage · 2025', 'A monumental cultural landscape where mountain ecology, sacred meaning, oral tradition and livelihoods meet.', 'Mulanje is more than a hiking destination. Its forests, peaks, water systems, stories and spiritual associations form a living landscape cared for through generations of community knowledge.', 'Southern Region', true, 2),
  ('lake-malawi', 'Lake Malawi', 'Northern, Central & Southern shores', 'Cultural Landscapes', 'https://commons.wikimedia.org/wiki/Special:Redirect/file/Lake%20Malawi%20%282416718857%29.jpg?width=1600', 'Living lakeshore landscape', 'The lake shapes movement, food, work, memory and identity across hundreds of shoreline communities.', 'This broader lakeshore story sits alongside the protected Lake Malawi National Park, connecting fishing knowledge, boat building, trade, ceremony and everyday life along the water.', 'Across Malawi', true, 3),
  ('lake-malawi-national-park', 'Lake Malawi National Park', 'Cape Maclear, Mangochi', 'Natural Heritage', 'https://commons.wikimedia.org/wiki/Special:Redirect/file/Sunset%20in%20lake%20malawi.jpg?width=1600', 'UNESCO World Heritage · 1984', 'A protected freshwater landscape recognised for exceptional biodiversity and the evolutionary importance of its fish species.', 'Clear waters, rocky islands and shoreline habitats create a place for conservation, research, community livelihoods and carefully managed visitor experiences.', 'Southern Region', true, 4),
  ('nyika-plateau', 'Nyika Plateau', 'Rumphi & Chitipa', 'Natural Heritage', 'https://commons.wikimedia.org/wiki/Special:Redirect/file/Nyika%20grassland.jpg?width=1600', 'Highland wilderness', 'Rolling montane grasslands, wildflowers and far-reaching views define Malawi''s largest high plateau.', 'Nyika rewards slow travel through high-altitude landscapes that support distinctive plants, birds and wildlife while connecting with the neighbouring Vwaza conservation system.', 'Northern Region', true, 5),
  ('mua-mission', 'Mua Mission & Kungoni', 'Mua, Dedza', 'Archaeological & Historical Places', 'https://commons.wikimedia.org/wiki/Special:Redirect/file/Mua%20Mission%20church.jpg?width=1600', 'Living cultural centre', 'A long-standing centre for cultural research, community knowledge, performance, carving and museum interpretation.', 'Mua brings mission history into conversation with Chewa, Ngoni and Yao cultural knowledge through collections, workshops, architecture and living artistic practice.', 'Central Region', true, 7),
  ('fort-mangochi-makanjira-corridor', 'Fort Mangochi & Makanjira Corridor', 'Mangochi', 'Archaeological & Historical Places', 'https://commons.wikimedia.org/wiki/Special:Redirect/file/Fort%20Johnston%20in%20present%20day%20Mangochi%2C%20Malawi.jpg?width=1600', 'UNESCO Tentative List · 2025', 'A historical corridor linking fortifications, trade, resistance and changing power around the southern lakeshore.', 'The corridor offers an opportunity to interpret regional histories through connected sites rather than a single monument, with careful attention to multiple community perspectives.', 'Southern Region', true, 8),
  ('karonga-fossilised-geoheritage-landscape', 'Karonga Fossilised Geoheritage Landscape', 'Karonga', 'Archaeological & Historical Places', 'https://commons.wikimedia.org/wiki/Special:Redirect/file/Karonga%20Museum.jpg?width=1600', 'UNESCO Tentative List · 2025', 'A northern landscape where geology, fossils and evidence of deep human history meet public learning.', 'Karonga''s fossil heritage connects field research, museum interpretation and the much longer environmental story of the Great Rift Valley.', 'Northern Region', true, 9),
  ('lake-chilwa-wetland', 'Lake Chilwa Wetland', 'Zomba, Phalombe & Machinga', 'Natural Heritage', 'https://commons.wikimedia.org/wiki/Special:Redirect/file/Fishing%20in%20Malawi.jpg?width=1600', 'UNESCO Tentative List · 2025', 'A dynamic wetland landscape supporting birdlife, fisheries and livelihoods shaped by changing water cycles.', 'Lake Chilwa demonstrates the close relationship between ecological resilience and community knowledge, making conservation and responsible access central to its story.', 'Southern Region', true, 10),
  ('khulubvi-mbona-rain-shrines', 'Khulubvi & Mbona Rain Shrines', 'Nsanje', 'Cultural Landscapes', 'https://commons.wikimedia.org/wiki/Special:Redirect/file/Gule%20wamkulu%2C%20the%20Big%20dance.jpg?width=1600', 'UNESCO Tentative List · 2025', 'A sacred landscape associated with rainmaking, guardianship and the enduring spiritual history of the Lower Shire.', 'Interpretation must be led by custodians and must clearly distinguish public knowledge from ceremonies, places and images that require permission.', 'Southern Region', true, 11),
  ('malawi-slave-heritage-route', 'Malawi Slave Heritage Route', 'Multi-region route', 'Archaeological & Historical Places', 'https://commons.wikimedia.org/wiki/Special:Redirect/file/St%20Peters%20Cathedral%20Likoma.jpg?width=1600', 'UNESCO Tentative List · 2025', 'A connected route interpreting difficult histories of enslavement, resistance, mission encounters and regional movement.', 'The route should centre evidence, descendant communities and careful language, helping visitors understand how local places connect with wider African and global histories.', 'Across Malawi', true, 12),
  ('malape-pillars', 'Malape Pillars Geological Heritage', 'Machinga', 'Natural Heritage', 'https://commons.wikimedia.org/wiki/Special:Redirect/file/Emperors%20View-%20Zomba.jpg?width=1600', 'UNESCO Tentative List · 2025', 'Distinctive geological formations offering a window into erosion, landscape change and Malawi''s deep natural history.', 'The site is best presented through clear geological interpretation, local guide knowledge and practical information that protects fragile formations.', 'Southern Region', true, 13),
  ('liwonde-national-park', 'Liwonde National Park', 'Machinga', 'Natural Heritage', 'https://commons.wikimedia.org/wiki/Special:Redirect/file/Lake%20Malawi%20%282416718857%29.jpg?width=1600', 'National park', 'A protected Shire River landscape supporting wildlife, wetlands and conservation-linked tourism.', 'The park''s story should connect biodiversity with rangers, neighbouring communities, conservation partnerships and the responsibilities of wildlife visitors.', 'Southern Region', true, 14)
on conflict (slug) where slug is not null do update set
  title = excluded.title,
  location = excluded.location,
  type = excluded.type,
  image = excluded.image,
  tag = excluded.tag,
  summary = excluded.summary,
  body = excluded.body,
  region = excluded.region,
  published = excluded.published,
  sort_order = excluded.sort_order;
